# Generated by Django 4.0.4 on 2022-04-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ishchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familiyasi', models.CharField(max_length=255)),
                ('yoshi', models.IntegerField(default=18)),
                ('kasbi', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Ishchilar',
            },
        ),
    ]
